Added Documentation
AMLResearchProject/ALL-Detection-System-For-Oculus-Rift pull request #5
Opened 2020-03-26 20:10 UTC by rishabhbanga

1. Created documentation for Windows Issues but named it as Issues.md to keep it generalized.
2. Created documentation to explain functioning of scripts in Scripts folder - Autopilot feature
3. Added Values for Windows 10 in CNN's README.md

2020-03-26 20:49 UTC, AdamMiltonBarker requested changes
Hi mate sorry changes:

- Name the file Windows-10.md not issues.md
- Changing the profiles links was a mistake on my part please can you leave the association links as they are but the individuals' profiles should point to research project website as we are in the RP repo. Sorry this was my fault. 
- To keep inline with all other repos, file names and directories should begin with capital letter.
- Were we not meant to make the scripts executable by the Scripts directory, I feel moving files is unrequired  step. 
- Line breaks ( & nbsp ; ) should always be present between level 1 titles to keep in line with the rest of our repos, this isn't a mistake but intentional. 
- File names should not have spaces in them, same for directories.
- sh scriptsSetup.sh should be CamelCase

I think this is all

2020-03-27 05:53 UTC, rishabhbanga commented
Hi,

1. I hope you read the description - Created documentation for Windows Issues but named it as Issues.md to keep it generalized. This is because in case people start facing issues in MAC and Linux it would be better to have a single source of information.
2. So change individual links like https://www.leukemiaresearchassociation.ai/team/adam-milton-barker to https://www.leukemiaresearchassociation.ai/ ? 
3. If you're talking about the shell scripts. They're always supposed to being with small letters, though just saw I left Autorun.sh with a Capital letter.
4. You never replied to that discussion citing it. I assumed you agreed with the idea of keeping some level of abstraction.
5. But does it mean we should keep it that ways? The point of removing it was to maintain some best practices to make the documentation clean and not with unnecessary gaps.
6. Not sure why you mentioned this, but I double checked and couldn't find any such gaps between the files and directories I uploaded.
7. scriptsSetup is Camel Case. Don't understand your comment here.

2020-03-27 05:54 UTC, rishabhbanga commented
Ah I saw I uploaded the Article Ideas.md! Yeah that wasn't supposed to go up. But we could keep it there?

2020-03-27 06:15 UTC, AdamMiltonBarker commented
Hi @rishabhbanga  it isn't required no mate.

2020-03-27 06:24 UTC, AdamMiltonBarker commented
1. This was a fix for Windows no? Issues is not a descriptive name.
2. No the names should point to profile on https://www.petermossamlallresearch.com
3. Capital letters for all file names and directories.
4. No requirement to move files around you can run it from the Scripts directory.
5. You removed some, they need to go back to keep inline with all repositories they are by design not fault if you see other repositories it has been like this for a long time no need to remove.
6. Shouldn't be there
7. CamelCase capital C's

Thanks Rishabh

2020-03-27 20:30 UTC, rishabhbanga commented
Pushed the changes. Javier doesn't have a profile on https://www.petermossamlallresearch.com so didn't change his.

Moreover since you mentioned only profiles Peter Moss Leukemia AI Research still points to https://www.leukemiaresearchassociation.ai

2020-03-28 23:14 UTC, AdamMiltonBarker requested changes

2020-03-28 23:14 UTC, AdamMiltonBarker commented on CNN/Scripts/ScriptsSetup.sh
> +cp Randomizer.sh ../Model/Data/Train/
The script is still moving files, this is unrequired and can be changed to run from the Scripts directory., To confirm, we do not need to move any files.

2020-03-28 23:14 UTC, AdamMiltonBarker commented on Documentation/AutoPilot.md
> +sh ScriptsSetup.sh
Include cd Scripts

2020-03-28 23:14 UTC, AdamMiltonBarker commented on Documentation/AutoPilot.md
> +sh Autorun.sh
Include cd Scripts

2020-03-28 23:15 UTC, AdamMiltonBarker commented
Thanks @rishabhbanga  just a few last changes that haven't been done yet then I believe we can merge your code. Thank you for the hard work.

2020-03-30 06:41 UTC, merged